import type { Metadata } from "next";
import { Atkinson_Hyperlegible_Next, Halant } from "next/font/google";
import "./globals.css";
import DynamicIsland from "./components/DynamicIsland";

const atkinsonHyperlegible = Atkinson_Hyperlegible_Next({
	variable: "--font-atkinson",
	subsets: ["latin"],
	weight: ["400", "500", "600", "700"],
});

const halant = Halant({
	variable: "--font-halant",
	subsets: ["latin"],
	weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`flex flex-col items-center ${atkinsonHyperlegible.variable} ${halant.variable} antialiased bg-background`}
			>
				<DynamicIsland />
				<div id="smooth-wrapper">
					<div id="smooth-content">{children}</div>
				</div>
			</body>
		</html>
	);
}
